# Generated by Django 5.1 on 2024-09-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0004_berserkarmy_berserkcreature_berserkcharacter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berserkgeography',
            name='army',
        ),
        migrations.AlterField(
            model_name='berserkcharacter',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkarmy'),
        ),
        migrations.DeleteModel(
            name='Berserk',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
