# Generated by Django 5.1 on 2024-09-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0005_remove_berserkgeography_army_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berserkarmy',
            name='member',
        ),
    ]
