# Generated by Django 5.1 on 2024-10-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0006_remove_berserkarmy_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='berserkcharacter',
            name='picture',
            field=models.ImageField(null=True, upload_to='berserkCharacters', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='berserkartifact',
            name='harm_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_harm_to', to='berserk.berserkcreature'),
        ),
    ]
