# Generated by Django 5.1 on 2024-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0007_berserkcharacter_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berserkartifact',
            name='picture',
            field=models.ImageField(null=True, upload_to='berserkCharacters', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='berserkcharacter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='berserkCharacters', verbose_name='Изображение'),
        ),
    ]
