# Generated by Django 5.1 on 2024-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0008_berserkartifact_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berserkartifact',
            name='picture',
            field=models.ImageField(null=True, upload_to='berserkArtifact', verbose_name='Изображение'),
        ),
    ]
