# Generated by Django 5.1 on 2024-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0010_album_berserkcreature_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(null=True, upload_to='Album', verbose_name='Изображение'),
        ),
    ]
